### ISSUE TITLE
Spigot 1.8.1 error

### ISSUE THREAD

**Issue by Optigonnn** [Drepic26/CouponCodes3#16]

**Comment by Optigonnn** [comment]
Does not work.

**Comment by Drepic26** [comment]
It does work on spigot 1.8.1, and is what I compile against and build for. If you expect help, please provide a more detailed explanation of the error you are getting.

**Comment by Optigonnn** [comment]
[14:50:15] [Server thread/ERROR]: Could not load 'plugins\couponcodes-3.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/drepic26/couponcodes/bukkit/BukkitPlugin : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [server.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [server.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [server.jar:git-Spigot-952179b-e87122e]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]
Caused by: java.lang.UnsupportedClassVersionError: com/github/drepic26/couponcodes/bukkit/BukkitPlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_75]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_75]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_75]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-952179b-e87122e]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_75]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_75]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-952179b-e87122e]
	... 6 more

**Comment by Drepic26** [comment]
> java.lang.UnsupportedClassVersionError:  Unsupported major.minor version 52.0

Something seems to be wrong with the version of java you have installed.

What version of java are you running? This plugin has been tested against java 6,7, and 8.

**Comment by Optigonnn** [comment]
1.7.0 64bit.

**Comment by Drepic26** [comment]
I just tested it on my own machine with java 1.7.0_75, and had no errors. "Unsupported major.minor version 52.0" means that it requires java 8, although it shouldn't.
 I was still using a gradle buildscript during that release, which didn't allow me to specify a target java version. I've since switched to maven, which I've targeted for java 6 and above.

I've drafted a pre-release of my most recent changes which are just about ready for release anyway, try that and see if it works.
If it doesn't work, I recommend trying to re-install or update java

**Comment by Optigonnn** [comment]
It's the only plugin with the issue.

**Comment by Drepic26** [comment]
There's no doubt that the error is related to the java version, which is likely on my end due to having used gradle prior and compiling against java 1.8.1, while relying on Continuous Integration to make sure everything worked. If I am correct, this issue should be fixed on any version I compiled with maven. Still though, I am confused as to why it would work fine on my machine and not yours.

**Comment by Optigonnn** [comment]
I'm using it on my Windows PC (for testing/development) purposes, and RedeemMe doesn't work either..

**Comment by Drepic26** [comment]
Before I do a full release of a version I test it on windows 7/8, as well as ubuntu all with java 6 to make sure of compatibility. The pre-release I just drafted has only been tested on windows 10, but should work despite the os.

**Comment by Optigonnn** [comment]
Hmm interesting, I have JRE not JDK.

**Comment by Drepic26** [comment]
The only difference with the JRE and the jdk is that the jdk includes the tools to develop java applications. The JDK contains the JRE, and the JRE is used to run programs.

**Comment by Drepic26** [comment]
I have released a new version, please tell me if this one works. In this version, source compatibility has been targeted for java 6.
