### ISSUE TITLE
"/coupon add item" does not work when an amount is not specified

### ISSUE THREAD

**Issue by HaivoN** [Drepic26/CouponCodes3#19]
/coupon add item [coupon] [item]
Does not work anymore. It does nothing, but some error in console. I am using spigot 1.8.3.

[09:53:18] [Server thread/WARN]: [CouponCodes] Task #34773 for CouponCodes v3.1.3 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.drevelopment.couponcodes.bukkit.coupon.BukkitCouponHandler.itemStringToHash(BukkitCouponHandler.java:297) ~[?:?]
	at com.drevelopment.couponcodes.core.commands.runnables.AddCommand.run(AddCommand.java:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot_server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot_server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot_server.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot_server.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

**Comment by Drepic26** [comment]
what is the exact command you are running? Judging by the error, the [item] section is formatted wrong.

**Comment by HaivoN** [comment]
/coupon add item 123 stone
/coupon add item 123 1
/coupon add item 123 minecraft:stone
none of them working

**Comment by Drepic26** [comment]
The syntax for the command is <code>/coupon add item \<name> \<item1:amount,item2:amount,...></code>

This means that the command you should be running to add one stone block is <code>/coupon add item 123 stone:1</code>

I'll leave this issue open however, and make an improvement for when an amount is not specified.

**Comment by HaivoN** [comment]
Ok, thanks

**Comment by bclemmey** [comment]
To add to this, did you ever make a way for this to work with damage values? As far as I know, before I could only give someone white wool, or ordinary stone, but never any of the new stone, or different types of log or anything.

**Comment by Drepic26** [comment]
@bclemmey
That's covered by #9

**Comment by bclemmey** [comment]
Thanks! And of course, thanks for developing the plugin, it's of great use. 


     On Saturday, 6 June 2015, 12:54, Nicholas Feldman <notifications@github.com> wrote:
   

 @bclemmey
That's covered by #9—

**Comment by Drepic26** [comment]
Fixed in dd202c0
